In [1]:
from pathlib import Path
import os

if Path.cwd().name != 'src':
    os.chdir('/home/vaschetti/maxarSrc/src')

In [2]:
from maxarseg.assemble import names
events_names = names.get_all_events()

In [3]:
from maxarseg.configs import DetectConfig, SegmentConfig
#seg_config = SegmentConfig(batch_size = 1, device='cuda:2', size = 600, stride = 400)
det_config = DetectConfig(batch_size = 1,
                          device='cuda:2',
                          size = 600,
                          stride = 600,
                          TEXT_PROMPT='bush')

In [4]:
from maxarseg.assemble import holders, names

events_names = names.get_all_events()

event = holders.Event(events_names[6],
                      #seg_config = seg_config,
                      det_config = det_config,
                      when='pre')

print(event.region_name)

all_mosaics_names = event.all_mosaics_names
print(all_mosaics_names)

m0 = event.mosaics[all_mosaics_names[0]]
print(f'Number of tiles: {m0.tiles_num}')

AfricaWest-Full
['10300100CFC9A500', '105001002BD68F00', '1040010073D77D00']
Number of tiles: 18


In [5]:
from maxarseg.geo_datasets import geoDatasets
from maxarseg.samplers import samplers
from torch.utils.data import DataLoader
from torchgeo.datasets import stack_samples

dataset = geoDatasets.MxrSingleTileNoEmpty(str(m0.tiles_paths[17]))
sampler = samplers.BatchGridGeoSampler(dataset, batch_size=1, size=600, stride=400)
dataloader = DataLoader(dataset , batch_sampler=sampler, collate_fn=stack_samples)

In [9]:
type(next(iter(dataloader))['bbox'][0])

torchgeo.datasets.utils.BoundingBox

In [ ]:
from torchgeo.datasets.utils import BoundingBox

In [6]:
res = m0.detect_trees_tile(m0.tiles_paths[17])

final text_encoder_type: bert-base-uncased

- GD model device: cuda:2


 90%|█████████ | 810/900 [03:43<00:24,  3.62it/s]


Discarded empty chips:  90
True num of batch:  810.0


In [7]:
~(res.geometry.area > 6000).all()

True

In [8]:
res.to_file("trees_25_3_24_full")

In [7]:
res[0]

array([ 1808.9430542 , 16808.05786133,  2200.04272461,  2200.05755615])

In [14]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2])
a + b

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [13]:
r[0]

array([[ 2.0894305e+02,  5.7861328e-02,  6.0004272e+02,  6.0005756e+02],
       [ 2.3118320e+02,  4.3495026e+01,  2.6965045e+02,  1.0211229e+02],
       [ 4.7595953e+02, -7.7209473e-02,  6.0000555e+02,  3.4698505e+02],
       [ 2.8204865e+02, -3.4008789e-01,  4.7012793e+02,  3.5714130e+02],
       [ 2.0810159e+02,  2.4451244e+02,  2.6861993e+02,  3.5499356e+02],
       [ 2.7880759e+02, -1.3945007e-01,  5.9994080e+02,  3.5909802e+02],
       [ 2.7491299e+02, -7.7271461e-02,  3.0650290e+02,  2.6418896e+01],
       [ 2.7163971e+02, -3.3309937e-01,  6.0012323e+02,  5.9966614e+02]],
      dtype=float32)

In [6]:
box

tensor([[0.6742, 0.5001, 0.6518, 1.0000],
        [0.4174, 0.1213, 0.0641, 0.0977],
        [0.8966, 0.2891, 0.2067, 0.5784],
        [0.6268, 0.2973, 0.3135, 0.5958],
        [0.3973, 0.4996, 0.1009, 0.1841],
        [0.7323, 0.2991, 0.5352, 0.5987],
        [0.4845, 0.0220, 0.0526, 0.0442],
        [0.7265, 0.4994, 0.5475, 1.0000]])

In [11]:
from groundingdino.util.inference import Model
det = Model.post_process_result(source_h = 600,
                          source_w = 600,
                          boxes = box,
                          logits = log)

In [14]:
det.xyxy

array([[ 2.0894305e+02,  5.7861328e-02,  6.0004272e+02,  6.0005756e+02],
       [ 2.3118320e+02,  4.3495026e+01,  2.6965045e+02,  1.0211229e+02],
       [ 4.7595953e+02, -7.7209473e-02,  6.0000555e+02,  3.4698505e+02],
       [ 2.8204865e+02, -3.4008789e-01,  4.7012793e+02,  3.5714130e+02],
       [ 2.0810159e+02,  2.4451244e+02,  2.6861993e+02,  3.5499356e+02],
       [ 2.7880759e+02, -1.3945007e-01,  5.9994080e+02,  3.5909802e+02],
       [ 2.7491299e+02, -7.7271461e-02,  3.0650290e+02,  2.6418896e+01],
       [ 2.7163971e+02, -3.3309937e-01,  6.0012323e+02,  5.9966614e+02]],
      dtype=float32)

In [8]:
phr

['green tree', '', '', '', '', '', '', '']